#!/usr/bin/env bash
# Configure environment variables for MotionForesight inference.
# Source from the repository root after setting optional paths below.

export MOTIONFORESIGHT_ROOT="${MOTIONFORESIGHT_ROOT:-$(pwd)}"
export MOTIONFORESIGHT_ASSET_DIR="${MOTIONFORESIGHT_ASSET_DIR:-$MOTIONFORESIGHT_ROOT/assets}"
export MOTIONFORESIGHT_ENV="${MOTIONFORESIGHT_ENV:-$MOTIONFORESIGHT_ASSET_DIR/venv}"
export PY="${PY:-$MOTIONFORESIGHT_ENV/bin/python}"

export HF_HOME="${HF_HOME:-$MOTIONFORESIGHT_ASSET_DIR/hf_cache}"
export HF_HUB_CACHE="${HF_HUB_CACHE:-$HF_HOME/hub}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$MOTIONFORESIGHT_ASSET_DIR/xdg_cache}"
export MPLCONFIGDIR="${MPLCONFIGDIR:-$XDG_CACHE_HOME/matplotlib}"
export PIP_CACHE_DIR="${PIP_CACHE_DIR:-$MOTIONFORESIGHT_ASSET_DIR/pip_cache}"

export MOTIONFORESIGHT_CKPT="${MOTIONFORESIGHT_CKPT:-$MOTIONFORESIGHT_ROOT/checkpoints/trainedon_ss100k/best.pt}"
export MOTIONFORESIGHT_BASE="${MOTIONFORESIGHT_BASE:-$MOTIONFORESIGHT_ASSET_DIR/models_pretrained/trackcraft3r/model.safetensors}"
export MODELSCOPE_CACHE="${MODELSCOPE_CACHE:-$MOTIONFORESIGHT_ASSET_DIR/models_pretrained/wan_models}"

export MODELSCOPE_OFFLINE="${MODELSCOPE_OFFLINE:-1}"
export HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}"
export TRANSFORMERS_OFFLINE="${TRANSFORMERS_OFFLINE:-1}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"

mkdir -p "$MPLCONFIGDIR" "$HF_HOME" "$PIP_CACHE_DIR"

cat <<EOF2
MotionForesight environment configured.
PY=$PY
MOTIONFORESIGHT_CKPT=$MOTIONFORESIGHT_CKPT
MOTIONFORESIGHT_BASE=$MOTIONFORESIGHT_BASE
MODELSCOPE_CACHE=$MODELSCOPE_CACHE
EOF2
